---
- hosts: all
  gather_facts: no
  tasks:
    - name: Create Deployment Key
      ansible.builtin.user:
         name: "{{user}}"
         generate_ssh_key: yes
         ssh_key_bits: 2048
         ssh_key_file: ".ssh/{{keyname}}"
    - name: Read SSH public key
      slurp: src="/home/george/.ssh/id_rsa_jasmin.pub"
      register: public_key
    - debug: msg="{{ public_key['content'] | b64decode }}"
