---
- hosts: all
  gather_facts: false
  tasks:
    - name: get django app
      ansible.builtin.git:
        key_file: "/home/{{user}}/.ssh/cfstore_key"
        repo: https://github.com/NCAS-CMS/cfstore
        dest: "{{ repo_dir }}"
        version: demo_branch_website 
        accept_hostkey: true
        force: true
