---

- hosts: all
  gather_facts: no
  vars:
     venv: "/home/{{user}}/django"
  tasks:
    - name: python2 setuptools
      # Make sure python2 (running ansible) has setuptools 
      # so it can parse the (python3) executable requirement that follows
      # https://github.com/ansible/ansible/issues/47361#issuecomment-431705748
      become: yes
      package:
        name: python-setuptools
        state: present
    - name: Make sure we have virtualenv
      become: yes
      pip:
         executable: /opt/miniconda3/bin/pip3
         name: virtualenv
    - name: stick a few things in our parent conda 
      become: yes 
      shell: "/opt/miniconda3/bin/conda install -y -c conda-forge udunits2 pygraphviz"
    - name: now setup our django virtual env
      pip:
         name: django
         virtualenv_command:  /opt/miniconda3/bin/virtualenv
         virtualenv: "{{venv}}"
    - name: add gunicorn here (since it's strictly not an application requirement)
      pip: 
        name: gunicorn
        virtualenv_command:  /opt/miniconda3/bin/virtualenv
        virtualenv: "{{venv}}"
    - name: add application requirements
      pip:
         requirements: "/home/{{user}}/cfstore/requirements.txt"
         virtualenv: "{{venv}}"
         virtualenv_command:  /opt/miniconda3/bin/virtualenv
    - name: fix up udunits2
      ansible.builtin.blockinfile:
         path: "{{venv}}/bin/activate"
         insertafter: EOF
         block: |
            # because we need to join our pip installed cf-python to system installed udunits2
            UDUNITS2_XML_PATH='/opt/miniconda3/share/udunits/udunits2.xml'
            export UDUNITS2_XML_PATH
            #
    - name: crude hack to get django to see the udunits xml variable
      ansible.builtin.blockinfile:        
         path: "{{repo_dir}}/manage.py"
         insertbefore: "^try"
         block: |
            # because we need to join our pip installed cf-python to system installed udunits2
            os.environ['UDUNITS2_XML_PATH'] ='/opt/miniconda3/share/udunits/udunits2.xml'
            # FIXME: we really need to work out why this is happening